# Package Overview
package_name: local_polynomial_regression

pipeline_name: local_polynomial_regression
pipeline_save_file: local_polynomial_regression_output

# to set the random seed
random_state: 1

# default bandwidth, only for testing purposes, needs to be optimized in production
bandwidth: 1.0

# kernel for estimation
allowed_kernels:
  - gaussian
  - epanechnikov
kernel: gaussian

# the number of slices for CV bandwidth selection for local polynomial 
# estimation
n_sections: 15

# loss function to be optimized
allowed_loss_functions:
  - ls
  - MSE
loss: MSE

# sampling types for cross validation
allowed_sampling_types:
  - random
  - slices
sampling: random